### ISSUE TITLE
Detect blinking 

### ISSUE THREAD

**Issue by willwade** [AceCentre/EyeCommander#10]
As a professional we find many people might not be able to do the eye movements but blink is possible. We'd like a simple way of detecting voluntary blinks. Ie filtering out shorter blinks. 

Needed. Thoughts
- somehow use a opencv approach to this 
- or train a different or same model to detect it. Will need labelled data for this

**Comment by willwade** [comment]
- https://github.com/Asadullah-Dal17/Eyes-Position-Estimator-Mediapipe/tree/master/Eye_Tracking_part2
- https://aiphile.hashnode.dev/blinking-detection-and-counter-mediapipe-eye-tracking-part-1-and-2### 

Maybe of interest

**Comment by gavinhenderson** [comment]
Closing as this is done
