### ISSUE TITLE
Consent workflow

### ISSUE THREAD

**Issue by willwade** [AceCentre/EyeCommander#11]
Task for WW really
- [ ] Draft participant info leaflet / pdf. To be packaged in installer 
- [ ] Draft consent doc / pdf. To be packaged in installer 

Work with @Dkashkett and @lucashsg77 to get specifics right. 

NB. We aren't looking at doing a formal research study as yet. This is internal only. But we do need to have some process for patients who donate their data to the base model.

**Comment by gavinhenderson** [comment]
Closing this until we have the model integrated with the react app
