### ISSUE TITLE
Build NSIS Installer

### ISSUE THREAD

**Issue by willwade** [AceCentre/EyeCommander#12]
As a windows user I want a easy to install software package where I don't have to worry about file paths and it's familiar to my platform. 

Focus on Windows. 

- [ ] Build nsis installer. Icon. Readme and docs from consent work to be added. Example here  https://github.com/AceCentre/RelayKeys/blob/master/build-installer.nsi
- [ ] Add to GitHub action workflow https://github.com/NSIS-Dev/github-action-examples/blob/master/.github/workflows/windows-latest.yml

**Comment by willwade** [comment]
Started this NSIS installer- but not tested. @gavinhenderson

**Comment by gavinhenderson** [comment]
@willwade, looks good. I have a potentially silly question. How do we tell pyinstaller to use the nsis file?

**Comment by willwade** [comment]
So usually - if you would:
1. Install NSIS (https://nsis.sourceforge.io/Download)
2. path/to/makensis path/to/build.nsi (or run the GUI)

makensis is usually in the NSIS program files directory

**Comment by willwade** [comment]
See line 63 of that nsis file. That's the thing that needs chsnging depending on the location of the built exe from the pyinstaller output.

**Comment by gavinhenderson** [comment]
Ah got you, seems simple enough. 

The official NSIS team has some nice Github Actions demos aswell https://github.com/NSIS-Dev/github-action-examples

**Comment by gavinhenderson** [comment]
Another perhaps obvious question.

Whats the benefit of an installer over just running the exe directly?

**Comment by willwade** [comment]
Well mainly that the thing runs and you can direct to things like help files and uninstall stuff. I guess short answer to that is support. If you use a installer you know the thing is properly working. Right now you are right - there isnt a big benefit. It might get more useful down the line if we need to do things like add more files or support material..

**Comment by gavinhenderson** [comment]
We use windows `squirrel` as our installer so this is no longer required
