### ISSUE TITLE
Action seems to be building example still..

### ISSUE THREAD

**Issue by willwade** [AceCentre/EyeCommander#16]
Thats wierd. Its built the binary for windows - but the example.py - not the eyecommander.py - so guessing there is another call to the pyinstaller python file Ive missed?

**Comment by gavinhenderson** [comment]
@willwade I had a quick look at the logs of the action and it seemed to use the `eyecommand.py` file as expected. What makes you think its using the `example.py`?

**Comment by willwade** [comment]
Could be me. I downloaded and ran it with a --help but it just ran like the old example. Maybe me!

**Comment by gavinhenderson** [comment]
Hmm, weird, it might not be passing through all the variables from the executable through to the python script so it just ignores them 🤔

**Comment by gavinhenderson** [comment]
I realise thats no help, just thinking out loud

**Comment by willwade** [comment]
My stupidity. Tried running ot with —help and no output. Should be fixed on next release I’m thinking. Not sure why -help doesn’t work but at least I can see it was taking in Params so is being built (eg you can change camera value)
