### ISSUE TITLE
ConfigFile

### ISSUE THREAD

**Issue by willwade** [AceCentre/EyeCommander#25]
As a end user there is a lot of command line options. I want to be able to use a configfile as well as command line options. This will be particularly useful if I have to rerun it regularly (and on Windows its far easier to alter a txt file than pass arguments), 

Command line arguments are still useful. e.g. --calibrate  . In this instance the arguments SHOULD have precedence over the configfile

Possibly need to use https://pypi.org/project/click-configfile/

**Comment by gavinhenderson** [comment]
No longer relevant to react app
