### ISSUE TITLE
Allow changing what keys are pressed at run time

### ISSUE THREAD

**Issue by willwade** [AceCentre/EyeCommander#26]
Currently the 'Keyboard Emulator' output hardcodes the output as a press of the `space` key. We want to be able to be able to change which key is being pressed in the output settings.

You should be able to chose any key on the keyboard and it should allow you to pick a key by pressing the desired key. (Similar to how Grid 3 lets you select a key)

Notes:
* [You can see where the space key is hardcoded here](https://github.com/AceCentre/EyeCommander/blob/bbf2f9dfba7ed36986cf5b3a6947f720c71ed380/src/backend/robot-keyboard.js#L11)

**Comment by gavinhenderson** [comment]
This should also allow outputting key presses

**Comment by gavinhenderson** [comment]
Contact Guillaume Hessel once this feature has been added
