### ISSUE TITLE
Force running as administrator

### ISSUE THREAD

**Issue by gavinhenderson** [AceCentre/EyeCommander#35]
Currently on windows you have to run this application as administrator. This is a limitation cause by other software (such as Grid3) running with elevated privileges so to interact with them we must run as administrator.

You can use the [`request-execution-level`](https://electron.github.io/electron-packager/main/interfaces/electronpackager.win32metadataoptions.html#requested_execution_level) in `electron-packager` to force the installer to open as Admin.

However, this has a limitation in that when you run the installer it then installs the application to the administrator account and therefore won't create a desktop icon if you are not the administrator. 

Ideally we should install it not as admin and then elevate to admin when we run the application. Could be hard though

**Comment by willwade** [comment]
maybe a Solution is to install in Program Files..  https://www.authentise.com/post/electron-and-uac-on-windows

**Comment by gavinhenderson** [comment]
Thats a really useful blog post and which led to discovering the `request-execution-level` in electron packager. The flag in electron packager creates a manifest in the same way they have in this blog post.

However, the main problem with their approach is they go for a global install on the machine rather than a per user install. The reason you have to do this is because when you elevate to admin there is no way to know which user to install to because the application thinks the user is the admin, so you can't install it to the current user because you dont know if thats correct, so you have to do a machine wide install. A machine wide install would be fine for EyeCommander, it is unlikely that we will have multiple distinct EyeCommander users on one machine.

But the main problem is [our installer](https://github.com/Squirrel/Squirrel.Windows) doesn't support machine wide installs :( We might be able to hack it so that it does support machine wide installers, but that would be fragile and we would effectively end up building our own installer.

We can switch installer. Electron forge has one other windows installer plugin. https://www.electronforge.io/config/makers/wix-msi This might work for us, worth a try. We can try other installers but we would have to stop using electron-forge but I really don't want to do that because it does ALL the hard work when it comes to application packaging.

Its a messy problem :( If anyone picks this up let me know and I can talk you through everything I tried and why I gave up in the end.

I see three solutions:
* Try https://www.electronforge.io/config/makers/wix-msi
* Build a custom installer, keep it super simple. It will work but seems like reinventing the wheel slightly.
* Install it per user, then at runtime request admin rights. This is probably a bit hacky but if it works 🤷

**Comment by willwade** [comment]
How about running a script post install that changes the run as admin setting?
Either altering it via the shortcut or a registry entry. 

See method 2 & 3 at https://www.top-password.com/blog/make-your-program-always-run-as-administrator/

And this might be useful https://stackoverflow.com/questions/52724004/configure-electron-builder-to-run-powershell-script

**Comment by gavinhenderson** [comment]
Thats a good shout actually. Squirrel installer exposes the hooks you mentioned so it would be pretty straight forward to run method 3 after install! Glad we have a way forward cause i bashed my head against this for quite a while
