### ISSUE TITLE
Output option: Windows Messages

### ISSUE THREAD

**Issue by willwade** [AceCentre/EyeCommander#5]
We currently have a `output_keys` option which is great - however many AAC systems won't detect this. Not a lot we can do - but one commercial system ([Grid 3](http://thinksmartbox.com)) does support something called Windows Messages. Its of course a Windows Only API. For this then means we need to build in a Windows Only requirement..

A code sample is seen attached - This is however not python. So we will need another library (!) win32api  https://stackoverflow.com/questions/14788036/python-win32api-sendmesage (I think this should do it)

I'm imagining this would be an option alongside the output_keys (so Output: False | WindowsMessages | Keys) 

[Sensory Switch[1].zip](https://github.com/AceCentre/EyeCommander/files/6971175/Sensory.Switch.1.zip)
How to find the Third Party Switch Interface in Grid 3 to test: https://user-images.githubusercontent.com/229352/129537895-70e5a5b9-957d-48d8-b2ba-776bfc75e6c5.mov

**Comment by gavinhenderson** [comment]
This is now built in
