### ISSUE TITLE
Stop detecting blinks when face is out of frame

### ISSUE THREAD

**Issue by willwade** [AceCentre/EyeCommander#54]
If you drop your head or have your head slightly off screen It starts clicking away as it thinks one eye is shut.. Maybe if we have an option to auto pause when the full face outline is not seen by the screen

**Comment by gavinhenderson** [comment]
Yeah it should just stop looking for blinks if your not in the frame. Not sure it needs to be an option it should just stop looking when your out of frame.

What blink mode does this happen on? Or all of them?

**Comment by willwade** [comment]
Yes to all of them. Just had a chat with a client whose been finding it a bit of a pain this one.

**Comment by gavinhenderson** [comment]
Moved it to the top of the list, will get to it straight after fixing running as admin (which I hope to finish soon)
