### ISSUE TITLE
Option: Configure which eye directions to detect

### ISSUE THREAD

**Issue by willwade** [AceCentre/EyeCommander#7]
Thinking a lot of people won't need to detect some directions.. Or simply cant move their eyes..

So really need a way of configuring to detect which named directions: Up,Down,Left,Right,Centre,(Blink?)

guessing a param option?

**Comment by Dkashkett** [comment]
I just created this PIR: []( https://github.com/AceCentre/EyeCommander/pull/9 ) 

It includes a solution to this issue, a parameter called directions which takes a list of strings. You can choose from 'left', 'right', 'up' and 'down', and the default is all of them. The 'center' class is necessary for the model so it will be added to the list no matter what options are specified. The default is all 5 directions, if no direction param is specified. 

This param will exclude directions that are unspecified from calibration and will ignore those directions during use. 

Blinking is a separate issue though. It is not currently built into our model, and adding it requires creating a new model with six classes, or a separate model that just predicts blinking. There are some unique challenges to blink detection, we need a large amount of data of people with their eyes closed to get the job done, which I don't currently have. But we can open a separate issue to discuss it.

**Comment by Dkashkett** [comment]
this is the link:

https://github.com/AceCentre/EyeCommander/pull/9
