### ISSUE TITLE
Need a way of sending training data back to add to model

### ISSUE THREAD

**Issue by willwade** [AceCentre/EyeCommander#8]
.. to discuss..

how do we do this.. ? Manually? (Upload it to us..)

And need to know how @Dkashkett  does the magic in adding training data to a model!

**Comment by Dkashkett** [comment]
At the moment it seems like manually is the way. If you or a care provider are using the app you would just specify keep_data and then you could upload the data. If you want I could look into how the data could be sent automatically? I know how to send emails with python, so sending files is likely possible as well. 

To add the new training data you can either retrain the current baseline model on the new data, which is cnn_filtered.h5, or build and train a whole new model which is usually what I do.

**Comment by willwade** [comment]
How big is the data that needs to be sent back? Maybe too big for email?

**Comment by Dkashkett** [comment]
around 3-4 megabytes. maybe a little bigger if they were using a nicer camera. but if we compressed it we could cut that down a bit.

**Comment by willwade** [comment]
Yeah. Maybe manually is the right way. Particularly as it's to only known people who have consented. We may want to assist the manual operation though. This is where having a Utility in the command line app may come in useful. --package-data=path and it would zip up the directory and pop it in that path.

**Comment by Dkashkett** [comment]
That makes sense, I think thats probably best too. I can write that up as a parameter so that you can pass in a path as an argument.

**Comment by gavinhenderson** [comment]
Closing this for now, we can reopen once we integrate the model into the electron app
